### ISSUE TITLE
Unsupported operation: RawSocket constructor, Web connection 

### ISSUE THREAD

**Issue by SunChilbd** [insinfo/galileo#3]
When trying to connect in chrome that error pops up. I thin web platform don't support socket.

_Error: Unsupported operation: RawSocket constructor
    at Object.throw_ [as throw] (http://localhost:58133/dart_sdk.js:5061:11)
    at Function.connect (http://localhost:58133/dart_sdk.js:57259:17)
    at defaultSocketFactory (http://localhost:58133/packages/dart_mysql/src/buffered_socket.dart.lib.js:155:29)
    at connect (http://localhost:58133/packages/dart_mysql/src/buffered_socket.dart.lib.js:167:40)
    at connect.next (<anonymous>)
    at runBody (http://localhost:58133/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:58133/dart_sdk.js:38690:7)
    at Function.connect (http://localhost:58133/packages/dart_mysql/src/buffered_socket.dart.lib.js:165:20)
    at connect (http://localhost:58133/packages/dart_mysql/src/single_connection.dart.lib.js:255:60)
    at connect.next (<anonymous>)
    at runBody (http://localhost:58133/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:58133/dart_sdk.js:38690:7)
    at Function.connect (http://localhost:58133/packages/dart_mysql/src/single_connection.dart.lib.js:239:20)
    at getConnection (http://localhost:58133/packages/flutter_application_basic/db/mysql.dart.lib.js:20:56)
    at getConnection.next (<anonymous>)
    at runBody (http://localhost:58133/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:58133/dart_sdk.js:38690:7)
    at mysql.MySql.new.getConnection (http://localhost:58133/packages/flutter_application_basic/db/mysql.dart.lib.js:17:20)
    at main.LoginPageState.new.connectar (http://localhost:58133/packages/flutter_application_basic/main.dart.lib.js:554:15)
    at http://localhost:58133/packages/flutter_application_basic/main.dart.lib.js:562:24
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:58133/packages/flutter/src/material/icon_button.dart.lib.js:33835:31)   
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:58133/packages/flutter/src/gestures/recognizer.dart.lib.js:185:18)      
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:58133/packages/flutter/src/gestures/tap.dart.lib.js:393:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:58133/packages/flutter/src/gestures/tap.dart.lib.js:205:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:58133/packages/flutter/src/gestures/tap.dart.lib.js:154:23)       
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:58133/packages/flutter/src/gestures/recognizer.dart.lib.js:428:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:58133/packages/flutter/src/gestures/pointer_router.dart.lib.js:85:9)   
    at http://localhost:58133/packages/flutter/src/gestures/pointer_router.dart.lib.js:115:26
    at LinkedMap.new.forEach (http://localhost:58133/dart_sdk.js:26433:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes]
    (http://localhost:58133/packages/flutter/src/gestures/pointer_router.dart.lib.js:113:29)
    at pointer_router.PointerRouter.new.route (http://localhost:58133/packages/flutter/src/gestures/pointer_router.dart.lib.js:108:37)       
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:362:26)     
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:347:24)   
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:58133/packages/flutter/src/rendering/layer.dart.lib.js:5118:13)   
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:58133/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:58133/dart_sdk.js:179667:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:58133/dart_sdk.js:160119:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:58133/dart_sdk.js:160965:49)
    at http://localhost:58133/dart_sdk.js:161384:28
    at http://localhost:58133/dart_sdk.js:161340:16
    at loggedHandler (http://localhost:58133/dart_sdk.js:161058:11)_

**Comment by insinfo** [comment]
You cannot use this in a browser, only in server side, CLI, flutter desktop or flutter mobile applications.
